# Data cleaning in Python with pandas

##  Setup

With this Google Colaboratory (Colab) notebook open, click the "Copy to Drive" button that appears in the menu bar. The notebook will then be attached to your own Google user account, so you can edit it in any way you like -- you can even take notes directly in the notebook.

## Agenda

1. **Guided instruction**: An instructor will work through the guided activity and teach concepts along the way.

2. **Collaborative exercises**: After the guided portion of the workshop, we will have time to work collaboratively on provided exercises, ask questions, and discuss any concepts relevant to the materials. (Exercises can also be completed outside of the meeting time. A link to the filled version of this notebook containing all of the completed code is available at the end of the notebook under the section *Further resources* for reference)

## Learning objectives

By the end of our workshop today, we hope you'll understand what the pandas library is and be able to use pandas to load, explore, and manipulate data.

### Today's Topics

- Reading and writing data files

- Exploring dataset characteristics

- Manipulating a dataset (adding/removing/editing data)

- Filtering a dataset

### Using Jupyter Notebooks and Google Colaboratory

Jupyter notebooks are a way to write and run Python code in an interactive way. They're quickly becoming a standard way of putting together data, code, and written explanations or visualizations into a single document and sharing that. There are a lot of ways that you can run Jupyter notebooks, including just locally on your computer, but we've decided to use Google's Colaboratory notebook platform for this workshop.  Colaboratory is “a Google research project created to help disseminate machine learning education and research.”  If you would like to know more about Colaboratory in general, you can visit the [Welcome Notebook](https://colab.research.google.com/notebooks/welcome.ipynb).

Using the Google Colaboratory platform allows us to focus on learning and writing Python in the workshop rather than on setting up Python, which can sometimes take a bit of extra work depending on platforms, operating systems, and other installed applications. If you'd like to install a Python distribution locally, though, we're happy to help. Feel free to [get help from our graduate consultants](https://www.lib.ncsu.edu/dxl) or [schedule an appointment with Libraries staff](https://go.ncsu.edu/dvs-request).

## Guided Instruction

**Content Warning:** This dataset contains information relating to violence towards animals. We understand that this may be distressing, and if you need to step away from the workshop we understand.

In this section, we will work through examples using data from the [Federal Aviation Administration (FAA) Wildlife Strikes Database](https://wildlife.faa.gov/search). We have filtered the data to only include North Carolina.

> "The FAA Wildlife Strike Database contains records of reported wildlife strikes since 1990. Strike reporting is voluntary. Therefore, this database only represents the information we have received from airlines, airports, pilots, and other sources." - [FAA website](https://wildlife.faa.gov/home)

### Import the data and the pandas library

To start, we must first load the pandas library into our Python environment and load in our datasets

#### Import pandas

Pandas is a high-level data manipulation tool first created in 2008 by Wes McKinney. The name comes from the term “panel data,” an econometrics term for data sets that include observations over multiple time periods for the same individuals.<sup>[[wikipedia](https://en.wikipedia.org/wiki/Pandas_(software))]</sup>

From Jake Vanderplas’ book [*Python Data Science Handbook*](http://shop.oreilly.com/product/0636920034919.do):

> As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

#### What does Pandas do?

- Reading and writing data from persistent storage

- Cleaning, filtering, and otherwise preparing data

- Calculating statistics and analyzing data

- Visualization with help from the Matplotlib plotting library

In [1]:
# Import the Pandas library as pd (callable in our code as pd)
import pandas as pd

#### Import datasets

We have prepared the data from the FAA website for this workshop. We will import those datasets into our notebook to use them for this activity.

- [Preview the CSV file (opens on GitHub)](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_strikes_1990-1999.csv) - wildlife strike data from the years 1990-1999
-[Preview the Excel file (this link will download the file)](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_strikes_2000-2009.xlsx?raw=true) - wildlife strike data from the years 2000-2009
- [Preview the JSON file (opens on GitHub)](https://raw.githubusercontent.com/NCSU-Libraries/data-viz-workshops/master/Python_Open_Labs/data/FAA_Wildlife_strikes_2010-2019.json) - wildlife strike data from the years 2010-2019

In [4]:
# Import the CSV file (wildlife strike data from the years 1990-1999)
csv_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_strikes_1990-1999.csv'
csv_df = pd.read_csv(csv_file_url)

# Print out the first five filas of the dataset
csv_df.head()

,INDX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,633309,1999-12-24,12,1999,10:15,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,18R,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Air Transport Operations,2000-03-10,False
1,634726,1999-12-15,12,1999,,Day,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,/Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,NaN,2000-03-09,False
2,636216,1999-12-14,12,1999,07:40,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,18R,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Tower,2000-03-09,False
3,633739,1999-12-11,12,1999,17:00,Dusk,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36R,NC,...,Large,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Tower,2000-03-09,False
4,636671,1999-12-11,12,1999,,NaN,KRDU,RALEIGH-DURHAM INTL,,NC,...,Medium,NaN,NaN,SOURCE = X AIRLINE REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,2001-06-25,False

In [5]:
# Import the Excel file (wildlife strike data from the years 2000-2009)
xls_file_url = 'https://github.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/blob/main/data/FAA_Wildlife_strikes_2000-2009.xlsx?raw=true'
xls_df = pd.read_excel(xls_file_url)

# Print out the first five columns of the dataset
xls_df.head()

,INDX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,707074,2009-12-24,12,2009,07:52,Dawn,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,Small,NaN,NaN,/Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Airport Operations,2010-04-29,False
1,707361,2009-12-13,12,2009,,Day,KILM,WILMINGTON INTL,17,NC,...,Medium,NaN,NaN,XXXX-XX-XX-XXXXXX /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2010-04-29,False
2,707050,2009-12-11,12,2009,07:26,Day,KILM,WILMINGTON INTL,35,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X (XXXX-XX-XX-XXXXXX & XXXXX...,REDACTED,REDACTED,FAA Form 5200-7-E,Air Transport Operations,2010-04-08,False
3,707146,2009-12-10,12,2009,16:45,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,Small,NaN,NaN,SOURCE = THREE XXXX-X (XXXX-XX-XX-XXXXXX & RX)...,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2010-08-19,False
4,707624,2009-12-08,12,2009,07:30,Dawn,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,,NC,...,Small,NaN,NaN,/Legacy Record=XXXXXX/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,2010-04-29,False

In [6]:
#Import the JSON file (wildlife strike data from the years 2010-2019)
json_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_strikes_2010-2019.json'
json_df = pd.read_json(json_file_url)
# Print out the first five columns of the dataset
json_df.head()

,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,FAAREGION,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
1080125,2020-11-05,11,2020,05:00,None,KRDU,RALEIGH-DURHAM INTL,23R,NC,ASO,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1080118,2020-11-05,11,2020,22:35,None,KGSO,PIEDMONT TRIAD INTL,5R,NC,ASO,...,Large,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1080126,2020-11-05,11,2020,11:00,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,ASO,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1080130,2020-11-05,11,2020,06:52,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,ASO,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1078243,2020-11-04,11,2020,05:20,Dawn,KRDU,RALEIGH-DURHAM INTL,23R,NC,ASO,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-11-27,False

### Explore the data

Now that we have our data, we can use pandas to explore it. This can be useful if you are new to a dataset and want to understand what it contains.

#### Pandas data structures

Pandas uses two main data structures: `Series` and `DataFrame`. **The data we imported is structured as a `DataFrame`.**

<img src="https://raw.githubusercontent.com/NCSU-Libraries/data-viz-workshops/master/Data_Manipulation_with_Python/assets/nc_dataframes.png" alt="DataFrames are composed of Series" width="60%">

A `Series` is a one-dimensional array of indexed data, or a single column of data with labels. You can learn more about the Series data type in the [Pandas documentation for Series](https://pandas.pydata.org/pandas-docs/stable/reference/series.html).

A `DataFrame` is a two-dimensional array composed of two or more `Series`, similar to tabluar data (think of Excel). They have row labels (an `Index`) and column labels. You can learn more about the DataFrame data type in the [Pandas documentation for DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html).

A `DataFrame` is made up of `Series` in a similar way in which a table is made up of columns. The only restriction is that each column must be of the same data type. Many of the operations that can be performed on a `DataFrame` can also be performed on an individual `Series`.

#### Referencing and indexing a DataFrame

The pandas library provides utilities to easily reference specific columns and rows from our DataFrame.

##### Referencing columns

In [ ]:
# View column labels (headers)

In [ ]:
# Reference a column from a DataFrame

In [ ]:
# Reference multiple columns from a DataFrame

##### Referencing rows

In [8]:
# View the row index labels from a DataFrame
json_df.index

Index([1080125, 1080118, 1080126, 1080130, 1078243, 1080107, 1078005, 1067129,
       1066925, 1066740,
       ...
        709805,  709643,  710039,  710030,  710057,  709088,  709085,  710034,
        709048,  710700],
      dtype='int64', length=3334)

In [10]:
# Reference a row by index label using .loc

# Access first row of wl_strikes_csv by index label
# In this case the index label is 0
csv_df.loc[0]

# Access first row of wl_strikes_json by index label
# In this case the index label is not 0
json_df.loc[1080125]

INCIDENT_DATE             2020-11-05
INCIDENT_MONTH                    11
INCIDENT_YEAR                   2020
TIME                           05:00
TIME_OF_DAY                     None
                         ...
REPORTER_TITLE              REDACTED
SOURCE             FAA Form 5200-7-E
PERSON            Airport Operations
LUPDATE                   2020-12-04
TRANSFER                       False
Name: 1080125, Length: 90, dtype: object

In [15]:
# Reference multiple rows by index label (in this case the index label 0 through 2)
# Returns a DataFrame
csv_df.loc[0:2]

,INDX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,633309,1999-12-24,12,1999,10:15,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,18R,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Air Transport Operations,2000-03-10,False
1,634726,1999-12-15,12,1999,,Day,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,/Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,NaN,2000-03-09,False
2,636216,1999-12-14,12,1999,07:40,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,18R,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Tower,2000-03-09,False

In [16]:
# Reference a row or multiple rows by zero-based integer position

# Access first row of wl_strikes_csv by row integer value
# In this case the row is row 0
csv_df.iloc[0]

# Access first row of wl_strikes_json by row integer value
# In this case the row is also row 0
json_df.iloc[0]

INCIDENT_DATE             2020-11-05
INCIDENT_MONTH                    11
INCIDENT_YEAR                   2020
TIME                           05:00
TIME_OF_DAY                     None
                         ...
REPORTER_TITLE              REDACTED
SOURCE             FAA Form 5200-7-E
PERSON            Airport Operations
LUPDATE                   2020-12-04
TRANSFER                       False
Name: 1080125, Length: 90, dtype: object

In [14]:
# Reference multiple rows by row number (in this case rows 0 through 2)
# Note that this time the range doesn't include the stop number
csv_df.iloc[0:2]

,INDX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,633309,1999-12-24,12,1999,10:15,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,18R,NC,...,Small,NaN,NaN,SOURCE = TWO XXXX-X REPTS /Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,Air Transport Operations,2000-03-10,False
1,634726,1999-12-15,12,1999,,Day,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,/Legacy Record=XXXXXX/,REDACTED,REDACTED,FAA Form 5200-7,NaN,2000-03-09,False

##### Referenceing both rows and columns

In [17]:
# Referencing a subset of rows and columns using index and column labels
# Note that we're using a range of column labels instead of a list
# Make sure that your column range starts with the leftmost label
csv_df.iloc[0:5, 0:4]

   INDX_NR INCIDENT_DATE   INCIDENT_MONTH  INCIDENT_YEAR
0   633309     1999-12-24              12           1999
1   634726     1999-12-15              12           1999
2   636216     1999-12-14              12           1999
3   633739     1999-12-11              12           1999
4   636671     1999-12-11              12           1999

#### View summaries of a DataFrame

We can quickly generate summaries of our DataFrame to observe some basic statistics and information such as column data types and non-null value counts.

In [18]:
# Get the "shape" of the Dataframe (the number of rows and columns)
#Numero de filas a la derecha, numero de columnas a la izquierza
csv_df.shape

(669, 91)

In [19]:
# Get summary statistics of DataFrame columns using "describe()" (only includes
# numerical data types)
csv_df.describe()

,INDX_NR,INCIDENT_MONTH,INCIDENT_YEAR,ENROUTE STATE,AMO,EMA,EMO,AC_MASS,NUM_ENGS,ENG_1_POS,...,HEIGHT,SPEED,DISTANCE,AOS,COST_REPAIRS,OTHER_COST,COST_REPAIRS_INFL_ADJ,COST_OTHER_INFL_ADJ,NR_INJURIES,NR_FATALITIES
count,669.000000,669.000000,669.000000,0.0,639.000000,628.00000,620.000000,647.000000,647.000000,640.000000,...,622.000000,542.000000,211.000000,18.000000,16.000000,7.000000,16.000000,7.000000,3.0,0.0
mean,626943.282511,7.544096,1994.789238,NaN,26.032864,26.56051,13.229032,3.491499,2.060278,3.818750,...,746.172026,139.924354,0.654028,105.944444,53193.000000,5523.571429,100497.750000,9129.142857,1.0,NaN
std,37159.222694,2.882413,2.847754,NaN,24.238506,10.51654,14.268682,0.872439,0.410107,1.831294,...,1557.121925,38.821595,3.717234,334.724904,125021.768963,4954.843350,244639.428923,8437.919163,0.0,NaN
min,608234.000000,1.000000,1985.000000,NaN,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,0.000000,20.000000,0.000000,1.000000,100.000000,250.000000,168.000000,398.000000,1.0,NaN
25%,613346.000000,6.000000,1992.000000,NaN,11.000000,19.00000,4.000000,3.000000,2.000000,1.000000,...,0.000000,120.000000,0.000000,2.250000,3025.000000,2050.000000,4755.500000,3263.500000,1.0,NaN
50%,619597.000000,8.000000,1995.000000,NaN,21.000000,34.00000,10.000000,4.000000,2.000000,5.000000,...,100.000000,135.000000,0.000000,9.500000,12000.000000,5000.000000,18750.000000,7665.000000,1.0,NaN
75%,627351.000000,10.000000,1997.000000,NaN,36.000000,34.00000,10.000000,4.000000,2.000000,5.000000,...,737.500000,150.000000,0.000000,54.750000,29925.000000,7657.500000,50603.750000,13513.000000,1.0,NaN
max,829805.000000,12.000000,1999.000000,NaN,97.000000,37.00000,46.000000,4.000000,4.000000,7.000000,...,17000.000000,270.000000,40.000000,1440.000000,500000.000000,14000.000000,978000.000000,22288.000000,1.0,NaN

In [22]:
# Get summary statistics of single column using "describe()"
csv_df["HEIGHT"].describe()

count      622.000000
mean       746.172026
std       1557.121925
min          0.000000
25%          0.000000
50%        100.000000
75%        737.500000
max      17000.000000
Name: HEIGHT, dtype: float64

In [24]:
csv_df["TIME"].describe()

count       669
unique       65
top
freq        597
Name: TIME, dtype: object

In [26]:
csv_df["TIME"]

0      10:15
1
2      07:40
3      17:00
4
       ...
664
665    11:35
666
667    21:30
668
Name: TIME, Length: 669, dtype: object

In [27]:
type(csv_df["TIME"][0])

str

In [23]:
# Summarize column data types, non-null values, and memory usage using "info()"
csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 91 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   INDX_NR                669 non-null    int64
 1   INCIDENT_DATE          669 non-null    object
 2   INCIDENT_MONTH         669 non-null    int64
 3   INCIDENT_YEAR          669 non-null    int64
 4   TIME                   669 non-null    object
 5   TIME_OF_DAY            633 non-null    object
 6   AIRPORT_ID             669 non-null    object
 7   AIRPORT                669 non-null    object
 8   RUNWAY                 669 non-null    object
 9   STATE                  669 non-null    object
 10  FAAREGION              669 non-null    object
 11  LOCATION               10 non-null     object
 12  ENROUTE STATE          0 non-null      float64
 13  OPID                   669 non-null    object
 14  REG                    669 non-null    object
 15  FLT                    669 non-null    object
 16  AIRCRAFT               669 non-null    object
 17  AMA                    660 non-null    object
 18  AMO                    639 non-null    float64
 19  EMA                    628 non-null    float64
 20  EMO                    620 non-null    float64
 21  AC_CLASS               660 non-null    object
 22  AC_MASS                647 non-null    float64
 23  TYPE_ENG               647 non-null    object
 24  NUM_ENGS               647 non-null    float64
 25  ENG_1_POS              640 non-null    float64
 26  ENG_2_POS              608 non-null    float64
 27  ENG_3_POS              60 non-null     float64
 28  ENG_4_POS              4 non-null      float64
 29  PHASE_OF_FLIGHT        648 non-null    object
 30  HEIGHT                 622 non-null    float64
 31  SPEED                  542 non-null    float64
 32  DISTANCE               211 non-null    float64
 33  SKY                    583 non-null    object
 34  PRECIPITATION          575 non-null    object
 35  AOS                    18 non-null     float64
 36  COST_REPAIRS           16 non-null     float64
 37  OTHER_COST             7 non-null      float64
 38  COST_REPAIRS_INFL_ADJ  16 non-null     float64
 39  COST_OTHER_INFL_ADJ    7 non-null      float64
 40  INGESTED               669 non-null    bool
 41  INDICATED_DAMAGE       669 non-null    bool
 42  DAMAGE_LEVEL           637 non-null    object
 43  STR_RAD                669 non-null    bool
 44  DAM_RAD                669 non-null    bool
 45  STR_WINDSHLD           669 non-null    bool
 46  DAM_WINDSHLD           669 non-null    bool
 47  STR_NOSE               669 non-null    bool
 48  DAM_NOSE               669 non-null    bool
 49  STR_ENG1               669 non-null    bool
 50  DAM_ENG1               669 non-null    bool
 51  STR_ENG2               669 non-null    bool
 52  DAM_ENG2               669 non-null    bool
 53  STR_ENG3               669 non-null    bool
 54  DAM_ENG3               669 non-null    bool
 55  STR_ENG4               669 non-null    bool
 56  DAM_ENG4               669 non-null    bool
 57  STR_PROP               669 non-null    bool
 58  DAM_PROP               669 non-null    bool
 59  STR_WING_ROT           669 non-null    bool
 60  DAM_WING_ROT           669 non-null    bool
 61  STR_FUSE               669 non-null    bool
 62  DAM_FUSE               669 non-null    bool
 63  STR_LG                 669 non-null    bool
 64  DAM_LG                 669 non-null    bool
 65  STR_TAIL               669 non-null    bool
 66  DAM_TAIL               669 non-null    bool
 67  STR_LGHTS              669 non-null    bool
 68  DAM_LGHTS              669 non-null    bool
 69  STR_OTHER              669 non-null    bool
 70  DAM_OTHER              669 non-null    bool
 71  OTHER_SPECIFY          18 non-null     object
 72  EFFECT                 516 non-null    object
 73  EFFECT_OTHER           10 non-null     object
 74  SPECIES_ID             669 non-null    object
 75  REMARKS                536 non-null    object
 76  REMAINS_COLLECTED      669 non-null    bool
 77  REMAINS_SENT           669 non-null    bool
 78  WARNED                 669 non-null    object
 79  BIRDS_SEEN             669 non-null    object
 80  BIRDS_STRUCK           669 non-null    object
 81  SIZE                   669 non-null    object
 82  NR_INJURIES            3 non-null      float64
 83  NR_FATALITIES          0 non-null      float64
 84  COMMENT                669 non-null    object
 85  REPORTER_NAME          669 non-null    object
 86  REPORTER_TITLE         669 non-null    object
 87  SOURCE                 669 non-null    object
 88  PERSON                 389 non-null    object
 89  LUPDATE                669 non-null    object
 90  TRANSFER               669 non-null    bool
dtypes: bool(33), float64(20), int64(3), object(35)
memory usage: 324.8+ KB

### Manipulate the data

After exploring our data, we can use pandas to add, remove, and change data to create a dataset or multiple datasets that are more suited for our analyses.

#### Reset DataFrame index labels
The JSON file we imported does not include the column `INDX_NR`. Instead, these values are used as the index labels. We want this dataset to match the format of our other datasets, so we first need to reset the index using the DataFrame method `reset_index()`.

In [30]:
# Print out the first five rows of the JSON DataFrame
json_df.head()

# Reset the JSON DataFrame index, implece modifica el DataFrame, es decir le obliga
json_df.reset_index(inplace=True)

# Print out the first five rows of the dataset
json_df.head()

,index,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,1080125,2020-11-05,11,2020,05:00,None,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1,1080118,2020-11-05,11,2020,22:35,None,KGSO,PIEDMONT TRIAD INTL,5R,NC,...,Large,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
2,1080126,2020-11-05,11,2020,11:00,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
3,1080130,2020-11-05,11,2020,06:52,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
4,1078243,2020-11-04,11,2020,05:20,Dawn,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-11-27,False

#### Rename column labels

When we reset our index a new column `index` was created. Let's change the name of this column to `INDX_NR` to match our other datasets using the DataFrame `rename()` method.

In [31]:
type({"index":"INDX_MM"})

dict

In [37]:
d = {"index":"INDX_MM", 0:1}

d[0]
hash(1.2)

461168601842738689

In [39]:
# Rename the column we created

json_df.rename(columns={"index":"INDX_NR"},inplace=True)
# Print out the first five rows of the dataset
json_df.head()

,INDX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,RUNWAY,STATE,...,SIZE,NR_INJURIES,NR_FATALITIES,COMMENT,REPORTER_NAME,REPORTER_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER
0,1080125,2020-11-05,11,2020,05:00,None,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
1,1080118,2020-11-05,11,2020,22:35,None,KGSO,PIEDMONT TRIAD INTL,5R,NC,...,Large,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
2,1080126,2020-11-05,11,2020,11:00,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
3,1080130,2020-11-05,11,2020,06:52,Day,KCLT,CHARLOTTE/DOUGLAS INTL ARPT,36C,NC,...,None,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-12-04,False
4,1078243,2020-11-04,11,2020,05:20,Dawn,KRDU,RALEIGH-DURHAM INTL,23R,NC,...,Small,NaN,NaN,None,REDACTED,REDACTED,FAA Form 5200-7-E,Airport Operations,2020-11-27,False

#### Concatenate the three DataFrames

We want to be able to work with all of the data we have imported at once, so we need to pull all three DataFrames into one. They all have the same columns now, so we can concatenate them based on columns (similar to adding them together, one on top of another) using the pandas method `concat()`. We also need to consider the current index labels for each dataset. We will create a new zero-based integer index label for the concatenated dataset by passing the keyword argument `ignore_index=True` into the `concat()` method.

In [45]:
# Concatenate all the datasets into one
full_df = pd.concat([csv_df, xls_df, json_df], ignore_index=True)

# Print the shape (number of rows and columns) of the full DataFrame
full_df.shape

(4964, 91)

#### Merge DataFrames

Our dataset includes a column of species IDs (`SPECIES_ID`) that consist of alpha-numeric codes that reference a specific species of animal. This code is not very helpful if we want to know the species name of an animal involved in a strike. Let's join our dataset with another dataset containing unique species IDs and species names using the shared column `SPECIES_ID` to generate a new column of data (`SPECIES`) containing species name using `merge()`. The URL to the dataset of species IDs and names is stored in the variable `species_names_file_url`.

In [50]:
full_df["SPECIES_ID"]

0       O2111
1       UNKBS
2       YL001
3       UNKBL
4       UNKBM
        ...
4959      NE1
4960      NE1
4961      NE1
4962    UNKBS
4963    UNKBS
Name: SPECIES_ID, Length: 4964, dtype: object

In [53]:
# Load the species ID table (stored in a CSV file)
species_names_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_species_id_table.csv'

species_names_df = pd.read_csv(species_names_file_url)
# Print the loaded species ID table
species_names_df

    SPECIES_ID           SPECIES
0        ZX004   Dark-eyed junco
1        1F132   Common gray fox
2         UNKB      Unknown bird
3        Z6007    American robin
4        N5111          Killdeer
..         ...               ...
204      J2118  Hooded merganser
205      J2209             Brant
206      J2202        Snow goose
207        I13            Egrets
208       1F12      Domestic dog

[209 rows x 2 columns]

# ![Left join visual example](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/Data_wrangling_with_Pandas/left-join.png?raw=true)

In [57]:
# Create a new DataFrame from a "left" join of the full dataset and the species
# ID table based on the shared column "SPECIES_ID"
joined_df = pd.merge(full_df, species_names_df, how="left")

# Print out the columns "SPECIES" and "SPECIES_ID" from the new merged dataset
joined_df[["SPECIES","SPECIES_ID"]]

                    SPECIES SPECIES_ID
0               Rock pigeon      O2111
1      Unknown bird - small      UNKBS
2         European starling      YL001
3      Unknown bird - large      UNKBL
4     Unknown bird - medium      UNKBM
...                     ...        ...
4959                  Gulls        NE1
4960                  Gulls        NE1
4961                  Gulls        NE1
4962   Unknown bird - small      UNKBS
4963   Unknown bird - small      UNKBS

[4964 rows x 2 columns]

#### Removing unnecessary columns

We can reduce the size of our dataset by removing unnecessary columns of data using the DataFrame `drop()` method.

In [ ]:
# Remove the "STATE", "FAAREGION", and "COMMENT" columns using "drop()""


# Print out the shape of the new DataFrame (should only contain 89 columns)

#### Calculating new columns

We can add new data to our dataset by manipulating existing data.

##### Create a new column using an expression

We may want to add a new column that is calculated based on other columns. In this example, we create a new column (`SINGLE_OR_MULTI_ENGINE`) of boolean values that tells us if the plane was a single-engine (TRUE) or a multi-engine (FALSE) plane using a comparison operator to test if the value in the column `NUM_ENGS` equals 1.

In [ ]:
# Print out the "NUM_ENGS" column


# Create a new column of boolean values indicating single- or multi-engine


# Print out the new column

##### Create a new column using `apply()`

Sometimes you need to create a new column based on more complex manipulation of existing data. In this example, we use the `apply()` method to apply the function `calc_hour` along the rows in the column `TIME`. The `calc_hour` function parses an integer value of the hour from a string containing the time at which a strike occurred. We create a new column `HOUR` that contains a numerical representation of the hour in which a strike occurred.

In [ ]:
# Define a function that takes a time string in the form "HH:MM" and returns the
# hour as an integer if the hour value is valid
def calc_hour(time_str):
    # Split the string on the occurance of ":" and take the first value
    hour = time_str.split(':')[0]
    # If the string is not empty return the strint cast as an integer
    if hour.strip(' ') != '':
        return int(hour)

# Print out the "TIME" column


# Use the DataFrame apply() method to call calc_hour on the "TIME" column and
# create a new column "HOUR" in our DataFrame


# Print out the "TIME" and "HOUR" columns from our DataFrame

#### Replace values in a column

We can replace values in a column based on conditions, similar to "find and replace." In this example, we make our new `SINGLE_OR_MULTI_ENGINE` column more descriptive by changing `True` into " Single engine" and `False` into "Multi engine".

In [ ]:
# Replace True or False values with new strings, "Single engine" or "Multi engine"


# Print out the updated column of data

#### Filtering

We can filter our data using conditional statements. This can help us remove unecessary rows of data or observe a specific range of data.

In [ ]:
# Print out unique values from column "TIME_OF_DAY"


# Filter the data to only see incidents that happened at night


# Print out the filtered data

In [ ]:
# Filter the data using "INCIDENT_YEAR" to only see data from 2010 and after


# Print out the filtered data

In [ ]:
# Filter the data to only see incidents from 2010 and after that happened at
# night using the columns "TIME_OF_DAY" and "INCIDENT_YEAR"


# Print out the filtered data

### Write data to a file

After completing our manipulation, we may want to save our final dataset for future analyses.

In [ ]:
# Write to csv

## Collaborative exercises

We can use this time to work on the following exercises or ask questions.

### Exercise 1: Indexing cells

Use referencing and indexing to answer the following questions by finding the data in the rows, columns, and/or cells.

#### 1a. Time of day
Airlines are interested in when they should schedule flights to minimize collisions. What is the time of day for each incident? Create a `Series` of the time of day (`TIME_OF_DAY`)

In [ ]:
# Create a `Series` of the time of day (`TIME_OF_DAY`)


# Print new Series

#### 1b. Date and time
We want to find out when most of these collisions occur. What is the exact date and time of each incident? Print the third, fourth, and fifth columns from the data (`INCIDENT_MONTH`,	`INCIDENT_YEAR`, and	`TIME`).

In [ ]:
# Print the third, fourth, and fifth columns from the data
# (`INCIDENT_MONTH`, `INCIDENT_YEAR`, and `TIME`).

#### 1c. Access the 126th row

Use row indexing to find the data in the 126th row in the `wl_strikes_json` DataFrame. Check that your result is correct by making sure your `INCIDENT_DATE` value is `2020-07-17`.

> Tip: Remember that the integer-based row location is zero based

In [ ]:
# Access the 126th row from the 'wl_strikes_json` DataFrame

#### 1d. Cloud cover
A particular airline has nine flights that they want to compare to see if the cloud cover in the area had anything to do with the collision. Print rows 60-65 and the columns `INDX_NR`, `SKY`, `PHASE_OF_FLIGHT`, and `AIRPORT`

In [ ]:
# 2Print rows 60-65 and the columns 'INDX_NR', 'SKY', 'PHASE_OF_FLIGHT', and
# 'AIRPORT'

### Exercise 2: Rename column headers

Rename the column `REG` to the more descriptive `AIRCRAFT_REGISTRATION`

In [ ]:
# Change the column name "REG" to "AIRCRAFT_REGISTRATION"


# Print out the new DataFrame columns

### Exercise 3: Remove unnecessary columns

The are several columns of data that are not relevant for our analyses. Remove all columns related to engine and damage location (e.g., all the columns that begin with `ENG_`, `DAM_`, and `STR_`). A list of these column names is provided in the variable `drop_columns`.

**Bonus:** See if you can derive the column names in the list `drop_columns` from the dataset

In [ ]:
# A list of column names to remove from the DataFrame
drop_columns = ['ENG_1_POS', 'ENG_2_POS', 'ENG_3_POS', 'ENG_4_POS', 'STR_RAD',
                'DAM_RAD', 'STR_WINDSHLD', 'DAM_WINDSHLD', 'STR_NOSE',
                'DAM_NOSE', 'STR_ENG1', 'DAM_ENG1', 'STR_ENG2', 'DAM_ENG2',
                'STR_ENG3', 'DAM_ENG3', 'STR_ENG4', 'DAM_ENG4', 'STR_PROP',
                'DAM_PROP', 'STR_WING_ROT', 'DAM_WING_ROT', 'STR_FUSE',
                'DAM_FUSE', 'STR_LG', 'DAM_LG', 'STR_TAIL', 'DAM_TAIL',
                'STR_LGHTS', 'DAM_LGHTS', 'STR_OTHER', 'DAM_OTHER']

# Remove unnecessary columns


# Print out the new DataFrame columns

### Exercise 4: Filter out unnecessary rows

Our dataset should only contain data from the years 1990-2019. Remove any rows of data that contain strikes that occurred outside of this year range.

In [ ]:
# Filter out rows of data that contain strikes that occurred outside of the year
# range 1990-2019


# Print out the new filtered DataFrame

### Exercise 5: Join airline operator names with the full dataset

Our dataset contains a column of airline operator IDs (`OPID`). These IDs correspond with airline operator names (e.g., Delta Airlines, Military, United Airlines, etc.). We have another dataset that contains arline operator IDs (in a column named `OPID`) and the corresponding airline operator name (in a column named `OPERATOR`). The URL to this dataset is stored in the variable `op_name_file_url`. Load this dataset and use a left join to merge the operator name with the full dataset.

In [ ]:
# URL to the CSV file containing unique airline operator IDs and names
op_name_file_url = 'https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_operator_id_table.csv?raw=true'

# Load the operator ID and name dataset into a DataFrame


# Join airline operator names to the full dataset using matching operater IDs


# Print out the columns "OPID" and "OPERATOR" from the new merged DataFrame

### Exercise 6: Create a new column containing month names

Our dataset currently contains a column of integer values representing the month number in which a strike occurred (1-12). It would be helpful to have a column containing the month name (e.g., January, February, etc.). Calculate a new column labeled `MONTH_NAME` containing the month name in which a stike occurred.

**TIP:** There are multiple ways you could consider creating this new column (e.g., using `replace()` or `apply()`), but it might be helpful to have a way to map month numbers (1-12) to month names (January - December) (e.g., a list or dictionary).

In [ ]:
# Create a new column "MONTH_NAME" containing month names in which a strike occurred

## Further resources

### Filled version of this notebook

[Data Cleaning in Python with pandas filled notebook](https://colab.research.google.com/github/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/blob/main/Data_Cleaning_in_Python_with_pandas_filled.ipynb) - a version of this notebook with all code filled in for the guided activity and exercises.

### Learning resources

- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) - a free, online version of Jake VanderPlas' introduction to data science with Python, includes a chapter on data manipulation with pandas.
- [Python Programming for Data Science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html) - a website providing a great overview of conducting data science with Python including pandas.

### Finding help with pandas

The [Pandas website](https://pandas.pydata.org/) and [online documentation](http://pandas.pydata.org/pandas-docs/stable/) are useful resources, and of course the indispensible [Stack Overflow has a "pandas" tag](https://stackoverflow.com/questions/tagged/pandas).  There is also a (much younger, much smaller) [sister site dedicated to Data Science questions that has a "pandas" tag](https://datascience.stackexchange.com/questions/tagged/pandas) too.

## Credits

This workshop was created by Walt Gurley and Claire Cahoon, adapted from previous workshop materials by Scott Bailey and Simon Wiles, of Stanford Libraries.